/*
 * This source file was generated by the Gradle 'init' task
 */
package sing.cli

class Path2Json {
    String getGreeting() {
        return 'Hello World from Groovy!!!'
    }

    static void main(String[] args) {
        println new Path2Json().greeting
    }
}
