/*
 * This source file was generated by the Gradle 'init' task
 */
package sing.cli

import spock.lang.Specification

class Path2JsonTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Path2Json()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
